/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as StartRouteImport } from './routes/start'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCoachRouteImport } from './routes/_app/coach'
import { Route as AppPathsRouteImport } from './routes/_app/paths'
import { Route as AppPipelineRouteImport } from './routes/_app/pipeline'
import { Route as AppRunwayRouteImport } from './routes/_app/runway'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppPathsRoute = AppPathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppRunwayRoute = AppRunwayRouteImport.update({
  id: '/runway',
  path: '/runway',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/start': typeof StartRoute
  '/coach': typeof AppCoachRoute
  '/paths': typeof AppPathsRoute
  '/pipeline': typeof AppPipelineRoute
  '/runway': typeof AppRunwayRoute
}
export interface FileRoutesByTo {
  '/start': typeof StartRoute
  '/coach': typeof AppCoachRoute
  '/paths': typeof AppPathsRoute
  '/pipeline': typeof AppPipelineRoute
  '/runway': typeof AppRunwayRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/start': typeof StartRoute
  '/_app/coach': typeof AppCoachRoute
  '/_app/paths': typeof AppPathsRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/runway': typeof AppRunwayRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/start' | '/coach' | '/paths' | '/pipeline' | '/runway'
  fileRoutesByTo: FileRoutesByTo
  to: '/start' | '/coach' | '/paths' | '/pipeline' | '/runway' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/start'
    | '/_app/coach'
    | '/_app/paths'
    | '/_app/pipeline'
    | '/_app/runway'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  StartRoute: typeof StartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coach': {
      id: '/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paths': {
      id: '/_app/paths'
      path: '/paths'
      fullPath: '/paths'
      preLoaderRoute: typeof AppPathsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runway': {
      id: '/_app/runway'
      path: '/runway'
      fullPath: '/runway'
      preLoaderRoute: typeof AppRunwayRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCoachRoute: typeof AppCoachRoute
  AppPathsRoute: typeof AppPathsRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppRunwayRoute: typeof AppRunwayRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoachRoute: AppCoachRoute,
  AppPathsRoute: AppPathsRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppRunwayRoute: AppRunwayRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  StartRoute: StartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
